### ISSUE TITLE
Images don't dynamically update

### ISSUE THREAD

**Issue by chimeranzl** [basknol/MMM-ImageFileWatcher#2]
Hi,
This is almost exactly what I was after... almost!  I have a water tank on my property and so have created 11 x PNG images, from 0 = empty to 100 = full, in 10% increments (eg: tank-0.png, tank-10.png, tank-20.png and so on)  I have a script that runs every 5 minutes that checks an MQTT message which indicates the tanks water level, it then removes any existing files from the MMM-ImageFileWatcher 'imagesPaths' folder and adds in the PNG file that corresponds to the actual water level.  This works perfectly on the first file that is copied into that folder, but if I delete the file then copy a different one, the image doesn't get updated.
By definition of your module it monitors a folder and updates the image, but it doesn't seem to do this after it's run the first time?  Also, if I set the 'showtime' to say 5 seconds, it shows the image for 5 seconds then the image disappears off the screen. Is there an alternate way to get what I need displayed properly?  Or does the code need changing to suit?
Cheers

**Comment by basknol** [comment]
Hi @chimeranzl, currently this module is designed to show an image for a certain time. It will queue the images placed in the folder and show it one by one for the configured 'showtime'. Let me know if you are still looking for this kind of functionality to show an image continuously and update the image if a new image is copied in the folder. Maybe I can add this to the module.

**Comment by chimeranzl** [comment]
Hey thanks for the response and yes absolutely I’m still looking for this functionality if you could add that in would be most appreciated!

**Comment by basknol** [comment]
Hi @chimeranzl, 
I have created a dev branched and introduct a 'mode' configuration option. Please see the [dev branch](https://github.com/basknol/MMM-ImageFileWatcher/tree/dev) and readme there for an explanation of the mode option. 
I could not reproduce the issue you have with copying a different image, but the image doesn't get updated.
Can you please try to pull the dev branch and see if this change work for you after adding the configuration option mode to the module config and set the mode value to 'one_image'.

Please let me know the results.
